### ISSUE TITLE
Could not find library plugin reach_core/plugins/MultiplicativeFactory

### ISSUE THREAD

**Issue by AndyZe** [ros-industrial/reach#13]
I've just cloned/built the package and attempted to run the demo. At this command:

`roslaunch reach_core start.launch config_file:=`rospack find reach_demo`/config/params.yaml config_name:=reach_study`

I get this error:

> Could not find library corresponding to plugin reach_core/plugins/MultiplicativeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.

Check list:

- [ ] I made sure the workspace was sourced correctly

- [ ] I tried both install and no install:  `catkin config --no-install` & `catkin config --install`

- [ ] I ran `rosdep install --from-paths src --ignore-src -r -y`

- [ ] I'm on Ubuntu 18, Melodic

**Comment by marip8** [comment]
It looks like I changed the name of the plugin library in #12 and forgot to update the `plugin_description.xml` file accordingly. A quick fix would be to change the name of the library in `reach_core/plugin_description.xml`:
```diff
- <library path="lib/libplugins">
+ <library path="lib/libreach_core_plugins">
```

I can make a PR with the change and add some unit tests to `reach_core` and `moveit_reach_plugins` for testing the plugin loading

**Comment by AndyZe** [comment]
Whoa, thanks for the fast response. That sounds great

**Comment by AndyZe** [comment]
thanks for the fix!
