### ISSUE TITLE
Reach ROS2 branch

### ISSUE THREAD

**Issue by livanov93** [ros-industrial/reach#21]
I am working on a port of reach on ROS2 [here](https://github.com/livanov93/reach/tree/livanov/port-ros2). Can you open ros2 branch so I can create PR against it.

**Comment by AndyZe** [comment]
No response? That's weird. This is a useful package and livanov93 has put a lot of work into it. He's not asking for much, either.

**Comment by Levi-Armstrong** [comment]
I see a ros2 branch, but maybe it was just created.

**Comment by marip8** [comment]
This issue must have slipped by; apologies for the delay. Friendly pings generally appreciated. 

I just created the [`ros2` branch](https://github.com/ros-industrial/reach/tree/ros2). I'm not sure this is how I want to handle ROS1/ROS2 compatibility long-term though. Ultimately I think I would prefer to revise `reach_core` to be ROS-independent and replace the custom messages with regular c++ data structures. The ROS interaction could live in the plugins where we could differentiate between ROS1/ROS2. It would also be nice if we could have the ROS1/ROS2 plugin packages live in the same branch as well to reduce maintenance on the core code that doesn't really need ROS.

**Comment by AndyZe** [comment]
Cool, thank you. My opinion on ROS1/ROS2 is that the days of ROS1 are limited. Personally I wouldn't bother much with ROS1 maintenance anymore.

**Comment by nbbrooks** [comment]
Thanks everyone, this slipped our mind as well. Lovro was presenting some extensions to ROS2 reach yesterday and Andy noticed it was still on a fork.

As far as ROS 1/ROS 2 goes, the ROS-independence sounds like a good goal and a nice way to handle syncs. In our internal tooling, we rarely do any ROS1 maintenance as Andy said (vast majority of our work is ROS 2 now). For MoveIt, we are using the github mergify bot to sync **bug fixes** between MoveIt1/MoveIt2 and it has been a good experience.

**Comment by Levi-Armstrong** [comment]
> Cool, thank you. My opinion on ROS1/ROS2 is that the days of ROS1 are limited. Personally I wouldn't bother much with ROS1 maintenance anymore.

Is that true? I know several groups have done a lot to move things over to Conda Forge to further the life of ROS1.

**Comment by livanov93** [comment]
@Levi-Armstrong Thank you for opening the ros2 branch!
The new ROS2-related PRs are #22 (direct port tested on galactic) and #23 (introduces retrieval IK solver)
